### ISSUE TITLE
use autopxd in cmake

### ISSUE THREAD

**Issue by Freed-Wu** [elijahr/python-autopxd2#54]
`pyproject.toml`:

```toml
[build-system]
requires = ["scikit-build-core", "cython-cmake", "autopxd2"]
build-backend = "scikit_build_core.build"
```

`CMakeLists.txt`:

```cmake
  find_program(autopxd REQUIRED)
  execute_process(COMMAND "${autopxd}" "${CMAKE_CURRENT_SOURCE_DIR}/src/astyle/wrap.h" "${CMAKE_CURRENT_BINARY_DIR}/wrap.pxd")
  cython_transpile(src/astyle/__init__.py
    CYTHON_ARGS "-3I${CMAKE_CURRENT_BINARY_DIR}" LANGUAGE C OUTPUT_VARIABLE output)
```

Can we have something like https://github.com/scikit-build/cython-cmake ?
